baseURL = 'jitesh117.github.io/'
languageCode = "en-us"
title = "Jitesh117"
theme = "PaperMod"
cover_image = "images/cover.jpeg"

googleAnalytics = "G-CGJ4KC5CSM"

buildFuture = true

[outputs]
  home = ['html', 'rss','json']
  section = ['html', 'rss']
  taxonomy = ['html']
  term = ['html']

# [params.author]
# email = 'sahookumarjitesh@gmail.com'
# name = 'Jitesh Kumar Sahoo'

[params.homeInfoParams]
Title = "Hey, I’m Jitesh 👋"
Content = "I'm a Data Scientist and Flutter Developer. I write about Data Science, Python, Machine Learning and anything that is going on my mind. Currently, I'm exploring Machine Learning, Kaggle competitions, and my inner conscience."

[[params.socialIcons]]
name = "github"
url = "https://github.com/Jitesh117"

[[params.socialIcons]]
name = "kaggle"
url = "https://www.kaggle.com/jiteshkumarsahoo"

[[params.socialIcons]]
name = "twitter"
url = "https://x.com/Jitesh_117"


[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/Jitesh117/"

[[params.socialIcons]]
name = "RSS"
url = "https://jitesh117.github.io/index.xml"


[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[[menu.main]]
identifier = "posts"
name = "Blog"
url = "/blog/"

[[menu.main]]
identifier = "shelf"
name = "Shelf"
url = "/shelf/"

[[menu.main]]
identifier = "musings"
name = "Essays"
url = "/musings/"

[[menu.main]]
identifier = "archive"
name = "Archives"
url = "/archives/"

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"

[[menu.main]]
identifier = "search"
name = "Search"
url = "/search/"

[params]
mainSections = ["blog", "musings"]

hideSummary = true

comments = true

archives = true
 archiveSection = ["blog", "musings", ]

defaultTheme = "dark"
disableThemeToggle = true


ShowCodeCopyButtons = true
ShowPostNavLinks = true
ShowReadingTime = true
ShowShareButtons = true

search = true
searchPlaceholder = "Search..."

[params.cover]
linkFullImages = true

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1_000
threshold = 0.4
minMatchCharLength = 0
keys = [ "title", "permalink", "summary", "content" ]