baseURL = 'jitesh117.github.io/'
languageCode = "en-us"
title = "Jitesh's Blog"
theme = "PaperMod"
cover_image = "images/cover.jpeg"

googleAnalytics = "G-CGJ4KC5CSM"

buildFuture = true

[outputs]
  home = ['html', 'rss','json']
  section = ['html', 'rss']
  taxonomy = ['html']
  term = ['html']

# [params.author]
# email = 'sahookumarjitesh@gmail.com'
# name = 'Jitesh Kumar Sahoo'

[params.homeInfoParams]
Title = "Hey, I’m Jitesh 👋"
Content = "Exploring the ins and outs of software, with some commentary on life sprinkled in. Follow along as I break down tech, share useful tips, and maybe crack a bad joke or two."

[[params.socialIcons]]
name = "github"
url = "https://github.com/Jitesh117"

[[params.socialIcons]]
name = "kaggle"
url = "https://www.kaggle.com/jiteshkumarsahoo"

[[params.socialIcons]]
name = "twitter"
url = "https://x.com/Jitesh_117"


[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/Jitesh117/"

[[params.socialIcons]]
name = "RSS"
url = "https://jitesh117.github.io/index.xml"


[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "archive"
name = "Archive"
url = "/archive/"
weight = 2

[[menu.main]]
identifier = "posts"
name = "Blog"
url = "/blog/"
weight = 3

[[menu.main]]
identifier = "musings"
name = "Essays"
url = "/musings/"
weight = 4

[[menu.main]]
identifier = "vim_stuff"
name = "Vim Stuff"
url = "/vim_stuff/"
weight = 5

[[menu.main]]
identifier = "shelf"
name = "Shelf"
url = "/shelf/"
weight = 6

[[menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 7

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 8

[params]
mainSections = ["blog", "musings", "vim_stuff"]

hideSummary = true

comments = true

archives = true
 archiveSection = ["blog", "musings", "vim_stuff"]

defaultTheme = "dark"
disableThemeToggle = true


ShowCodeCopyButtons = true
ShowPostNavLinks = true
ShowReadingTime = true
ShowShareButtons = true

search = true
searchPlaceholder = "Search..."

[params.cover]
linkFullImages = true

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1_000
threshold = 0.4
minMatchCharLength = 0
keys = [ "title", "permalink", "summary", "content" ]
