# Site Configuration
baseURL = 'jitesh117.github.io/'
languageCode = "en-us"
title = "Jitesh's Blog"
theme = "PaperMod"
cover_image = "images/cover.jpeg"
googleAnalytics = "G-CGJ4KC5CSM"
buildFuture = true

# Output Formats
[outputs]
  home = ['html', 'rss', 'json']
  section = ['html', 'rss']
  taxonomy = ['html']
  term = ['html']

# Site Parameters
[params]
  mainSections = ["blog", "musings", "vim_stuff"]
  hideSummary = true
  comments = true
  archives = true
  archiveSection = ["blog", "musings", "vim_stuff"]
  defaultTheme = "dark"
  disableThemeToggle = true
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPageNums = true
  search = true
  searchPlaceholder = "Search..."
  disableScrollToTop = true


  # Home Page Information
  [params.homeInfoParams]
Title = "{{< terminal-prompt >}}"
Content = "### Hey! I'm Jitesh\n Welcome to my corner of the internet. This website is a personal blog which I use as a platform to document my learning journey and showcase it for the world to see. **Hop in!**"

  # Social Icons
  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/Jitesh117"

  [[params.socialIcons]]
  name = "email"
  url = "mailto:sahookumarjitesh@gmail.com"

  [[params.socialIcons]]
  name = "twitter"
  url = "https://x.com/Jitesh_117"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/Jitesh117/"

  [[params.socialIcons]]
  name = "kaggle"
  url = "https://www.kaggle.com/jiteshkumarsahoo"

  [[params.socialIcons]]
  name = "buymeacoffee"
  url = "https://buymeacoffee.com/jitesh117"

  [[params.socialIcons]]
  name = "RSS"
  url = "https://jitesh117.github.io/index.xml"

  # Cover Image Parameters
  [params.cover]
  linkFullImages = true

  # Search Settings
  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1_000
    threshold = 0.4
    minMatchCharLength = 0
    keys = [ "title", "permalink", "summary", "content" ]

# Menu Configuration
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 2

[[menu.main]]
identifier = "archive"
name = "Archive"
url = "/archive/"
weight = 3

[[menu.main]]
identifier = "posts"
name = "Blog"
url = "/blog/"
weight = 4

[[menu.main]]
identifier = "musings"
name = "Essays"
url = "/musings/"
weight = 5

[[menu.main]]
identifier = "vim_stuff"
name = "Vim Stuff"
url = "/vim_stuff/"
weight = 6

[[menu.main]]
identifier = "shelf"
name = "Shelf"
url = "/shelf/"
weight = 7

[[menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 8

# Markup and Syntax Highlighting Settings
[markup.highlight]
  codeFences = true
  guessSyntax = true
  lineNos = false
  noClasses = false
